config/routes.rb
Hw4::Application.routes.draw do
  get "jobseekers/edit"
  get "jobseekers/index"
  get "jobseekers/new"
  get "jobseekers/CSindex"
  devise_for :employees
  get "employees/new"
  get "employees/index"
  get "employees/delete"
  get "employees/show"
  resources :jobseekers
  resources :employees
  get "jobseekers/delete"
  get "jobseekers/show"
  get "employees/edit"
  get "home/index"
  root 'home#index'
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobseekers, :dependent => :destroy
	validates :name, length: {within: 3..40}
	validates :name, uniqueness:true
	validates :name, exclusion: { in: ['Vivek Raj', 'Barack Obama'], message: "%{value} is reserved"}
end

app/models/jobseeker.rb
class Jobseeker < ActiveRecord::Base
  belongs_to :employee, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_employee!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def index
    @employees = Employee.all.order(:name)
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(employee_params)
      redirect_to employee_path(@employee.id)
    else
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
  else
    render 'new'
  end
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :category, :company, :email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobseekers_controller.rb
class JobseekersController < ApplicationController
  def new
    @jobseeker = Jobseeker.new
  end

  def show
    @jobseeker = Jobseeker.find(params[:id])
  end

  def index
    @jobseekers = Jobseeker.all.order(:category).limit(5)
  end

  def CSindex
    @jobseekers = Jobseeker.where(category: "Computer Software")
  end

  def edit
    @jobseeker = Jobseeker.find(params[:id])
  end

  def update
    @jobseeker = Jobseeker.find(params[:id])
    if @jobseeker.update_attributes(jobseeker_params)
      redirect_to jobseeker_path(@jobseeker.id)
    else
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @jobseeker = Jobseeker.find(params[:id])
    @jobseeker.destroy
    redirect_to jobseekers_path
  end

  def create
    @jobseeker = Jobseeker.new(jobseeker_params)
    if @jobseeker.save
      Notifications.jobseeker(@jobseeker).deliver
      redirect_to jobseekers_path
  else
    render 'new'
  end
  end

  private
  def jobseeker_params
    params.require(:jobseeker).permit(:name, :category, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobseekers_helper.rb
module JobseekersHelper
end

app/views/employees/delete.html.erb
<h1>Employees#delete</h1>
<p>Find me in app/views/employees/delete.html.erb</p>

app/views/employees/edit.html.erb
<%= form_for(@employee) do |f| %>
	<div class="field">
	 	<p>name</p> 
	 	<%= f.text_field :name%>
 	</div>
 	<div class="field">
 		<p>category</p> 
 		<%= f.text_field :category%>
 	</div>
	<div class="field">
 		<p>company</p> 
 		<%= f.text_field :company%>
 	</div>
 	<div class="field">
 		<p>email</p> 
 		<%= f.text_field :email%>
 	</div>
	<div class="actions">
		<%= f.submit %>
 	</div>
<% end %>

app/views/employees/index.html.erb
<table>
	<tr>
		<td>name</td>
		<!--<td>category</td>
		<td>company</td> -->
		<td>email</td>
	</tr>
	<% @employees.each do |employee| %>
	<tr>
		<td><%= link_to employee.name, employee_path(employee.id) %></td>
		<!--<td><%= employee.category %></td>
		<td><%= employee.company %></td> -->
		<td><%= employee.email %></td>
		<td><%= link_to "edit employee", edit_employee_path(employee.id) %></td>
		<td><%= link_to "delete employee", employee, confirm: "are you sure you want to delete this employee?", method: :delete %> </td>
	</tr>
	<% end %>
</table>
<p> <%=link_to "Go to home page", root_path %> </p>

app/views/employees/new.html.erb
<%= form_for(@employee) do |f| %>
	<div class="field">
		<p>Name</p>
		<%= f.text_field :name%>
	</div>
	<div class="field">
		<p>Job Category</p>
		<%= f.text_field :category%>
	</div>
	<div class="field">
		<p>Company</p>
		<%= f.text_field :company%>
	</div>
	<div class="field">
		<p>Email</p>
		<%= f.text_field :email%>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<div class = "error-msg">
		<% if @employee.errors.any? %>
		<ul>
			<% @employee.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>
	</div>
	<p> <%=link_to "Go to home page", root_path %> </p>
<% end %>

app/views/employees/show.html.erb
<div>
	<h2><%= @employee.name %></h2>
	<p><%= @employee.category %></p>
	<p><%= @employee.company %></p>
	<p><%= @employee.email %></p>
	<p> <%=link_to "Show all employees", employees_path %> </p>
	<p> <%=link_to "Add more employees", new_employee_path %> </p>
	<p> <%=link_to "Go to home page", root_path %> </p>
</div>

app/views/home/index.html.erb
<p> <%=link_to "Add job seeker", new_jobseeker_path %> </p>
<p> <%=link_to "Show employees (you can add new employees by creating new accounts)", employees_path %> </p>
<p> <%=link_to "Show job seekers", jobseekers_path %> </p>
<p> <%=link_to "Show Computer Software job seekers", jobseekers_CSindex_path %> </p>


<% if employee_signed_in? %>
	<li>
		<%= link_to('Logout', destroy_employee_session_path, :method => :delete) %>
	</li>
	<% else %>
	<li>
		<%= link_to('Login', new_employee_session_path) %>
	</li>
<% end %>

app/views/jobseekers/CSindex.html.erb
<table>
	<tr>
		<td>name</td>
		<td>category</td>
		<td>email</td>
	</tr>
	<% @jobseekers.each do |jobseeker| %>
	<tr>
		<td><%= link_to jobseeker.name, jobseeker_path(jobseeker.id) %></td>
		<td><%= jobseeker.category %></td>
		<td><%= jobseeker.email %></td>
		<td><%= link_to "edit entry", edit_jobseeker_path(jobseeker.id) %> </td>
		<td><%= link_to "delete jobseeker", jobseeker, confirm: "are you sure you want to delete this jobseeker?", method: :delete %> </td>
	</tr>
	<% end %>
</table>
<p> <%=link_to "Go to home page", root_path %> </p>

app/views/jobseekers/delete.html.erb
<h1>Jobseekers#edit</h1>
<p>Find me in app/views/jobseekers/edit.html.erb</p>

app/views/jobseekers/edit.html.erb
<%= form_for(@jobseeker) do |f| %>
	<div class="field">
	 	<p>name</p> 
	 	<%= f.text_field :name%>
 	</div>
 	<div class="field">
 		<p>category</p> 
 		<%= f.text_field :category%>
 	</div>
 	<div class="field">
 		<p>email</p> 
 		<%= f.text_field :email%>
 	</div>
	<div class="actions">
		<%= f.submit %>
 	</div>
<% end %>

app/views/jobseekers/index.html.erb
<table>
	<tr>
		<td>name</td>
		<td>category</td>
		<td>email</td>
	</tr>
	<% @jobseekers.each do |jobseeker| %>
	<tr>
		<td><%= link_to jobseeker.name, jobseeker_path(jobseeker.id) %></td>
		<td><%= jobseeker.category %></td>
		<td><%= jobseeker.email %></td>
		<td><%= link_to "edit entry", edit_jobseeker_path(jobseeker.id) %> </td>
		<td><%= link_to "delete jobseeker", jobseeker, confirm: "are you sure you want to delete this jobseeker?", method: :delete %> </td>
	</tr>
	<% end %>
</table>
<p> <%=link_to "Add more jobseekers", new_jobseeker_path %> </p>
<p> <%=link_to "Go to home page", root_path %> </p>

<button class="btn"> 
	Click me if you're satisfied!
</button>

app/views/jobseekers/new.html.erb
<%= form_for(@jobseeker) do |f| %>
	<div class="field">
		<p>Name</p>
		<%= f.text_field :name%>
	</div>
	<div class="field">
		<p>Job Category</p>
		<%= f.text_field :category%>
	</div>
	<div class="field">
		<p>Email</p>
		<%= f.text_field :email%>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<p> <%=link_to "Go to home page", root_path %> </p>
<% end %>

app/views/jobseekers/show.html.erb
<div>
	<h2><%= @jobseeker.name %></h2>
	<p><%= @jobseeker.category %></p>
	<p><%= @jobseeker.email %></p>
	<p> <%=link_to "Show all job seekers", jobseekers_path %> </p>
	<p> <%=link_to "Add more jobseekers", new_jobseeker_path %> </p>
	<p> <%=link_to "Go to home page", root_path %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="notice"><%= notice %></p>
<p class = "alert"><%= alert %></p>

</body>
</html>

app/views/notifications/jobseeker.html.erb
<p>Hello new jobseeker! You have been officially added to our site. You will receive email updates about job opportunities.</p>

app/views/notifications/new_comment.html.erb
Notifications#new_comment

<%= @greeting %>, <%= @commentor %> 

app/views/notifications/new_employee.text.erb
Notifications#new_employee

<%= @greeting %>, <%= @commentor %> 